# Generated by Django 2.2.27 on 2024-05-12 02:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240509_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2024, 5, 12, 5, 19, 36, 917524), verbose_name='Опубликована'),
        ),
    ]
