# Generated by Django 2.2.27 on 2024-05-13 01:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20240512_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Опубликована'),
        ),
    ]
